baseURL = "/"
relativeurls = true
languageCode = "zh-cn"
title = "Shumin's blog"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Liu Shumin"
  description = "In solitude, where we are least alone."
  github = "Shuminn"
  twitter = "ShuminLoveSci"
  linkedin = "åˆ˜ä¹¦æ•"
  email = "shuminliu0-0@foxmail.com"
  url = "https://liushumin.zone/"
  keywords = "Vision, Neuroscience, Swimming, Reading, Food, Life"
  rss = true
  lastmod = true
  favicon = "/images/RG.png'"
  location = "China"
  userStatusEmoji = "ğŸ˜€"


  [[params.links]]
    title = "ResearchGate"
    href = "https://www.researchgate.net/profile/Shumin-Liu-7"
    icon = "/images/RG.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]