baseURL = "https://liushumin.zone/"
languageCode = "zh-cn"
title = "Shumin's blog"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Shumin"
  description = "â€œäººä¸€æ—¦æ²‰é†‰äºè‡ªèº«çš„è½¯å¼±ï¼Œå°±ä¼šä¸€å‘³åœ°è½¯å¼±ä¸‹å»ã€‚ä¼šåœ¨ä¼—ç›®ç½ç½ä¸­å€’ä¸‹ï¼Œå€’åœ¨è¡—å¤´ï¼Œå€’åœ¨æ¯”åœ°é¢æ›´ä½çš„åœ°æ–¹ã€‚â€"
  github = "Shuminn"
  twitter = "ShuminLoveSci"
  email = "shuminliu0-0@foxmail.com"
  rss = false
  lastmod = true
  favicon = "ğŸ„"
  location = "Beijing, China"
  userStatusEmoji = "â˜º"

  [[params.links]]
    title = "ResearchGate"
    href = "https://www.researchgate.net/profile/Shumin-Liu-7"
    icon = "images/RG.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]